---
- name: Update auditd rules on Linux servers
  hosts: all
  become: true
  vars:

    linux_auditd_file: "auditd.rules"
    linux_auditd_dest_path: "/etc/audit/rules.d/{{ linux_auditd_file }}"

  roles:
    - update_auditd_configuration
